python event_loop.py --sample="qcd"
python event_loop.py --sample="higgsportal_125_40_0p1ns"
python event_loop.py --sample="higgsportal_125_55_1ns"
python event_loop.py --sample="stau_300_0p1ns"
python event_loop.py --sample="stau_300_1ns"
python event_loop.py --sample="stau_300_stable"
python event_loop.py --sample="stau_100_stable"

python event_loop.py --sample="suep_mMed-200_mDark-1.0_temp-1.0"
python event_loop.py --sample="suep_mMed-600_mDark-1.0_temp-1.0"
